service: html-to-pdf

provider:
  name: aws
  runtime: nodejs12.x
  stage: production

functions:
  topdf:
    handler: handler.topdf
    events:
      - http:
          path: topdf
          method: post
